{{- if .Values.serviceLlmGateway.rabbitmq.connectionString }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "llm-gateway-app.fullname" . }}-rabbitmq
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "llm-gateway-app.labels" . | nindent 4 }}
type: Opaque
stringData:
  connection-string: {{ .Values.serviceLlmGateway.rabbitmq.connectionString | quote }}
{{- end }}
